saving_nr : '01'
model_nr : '01'

#get data
runname : "my_conus2"
grid : 'conus2'
water_year : 2006

#train HML
ml_model : 'HML_model' #python file with model

train_model_bool : false
plot_MSE_dev_bool : true
compute_overall_test_loss_bool : true
test_model_bool : true
which_test_samples_factor : 20
test_model_extreme_bool : true
save_estims_bool : false
save_extreme_estims_bool : false
input_shape_prints_bool : true
verbose_bool : true

lr_scheduler_bool : true
early_stopping_bool : true
early_stopper_wait : 20
early_stopper_acc_diff : 10.0

use_dropout_bool : true
nesterov_bool : true

train_data_ratio : 0.75
test_data_ratio : 0.15

n_dims2 : 150
n_dims1 : 150

n_epochs : 300
seed : 0
learning_rate : 1.0e-4
lr_gamma : 0.85

optimizer_momentum : 0.9

amt_steps_per_sample : 1
mini_batch_size_train : 128
mini_batch_size_vali : 128
accumulation_steps : 1


#use HML
huc : 11090101
gt_available_bool : true
plot_gt_bool : true
plot_pred_bool : true